### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by enorrmann** [Vampouille/superboucle#53]
loading a mono ogg sample

(python3:27115): Gtk-WARNING **: 14:36:05.107: Failed to measure available space: La ubicación especificada no está soportada
From cffi callback <function Client.set_process_callback.<locals>.callback_wrapper at 0x7fe6a92ce158>:
Traceback (most recent call last):
  File "/home/enorrmann/git/superboucle/jack.py", line 878, in callback_wrapper
    return callback(frames)
  File "boucle.py", line 145, in my_callback
    ch_id % song.channels(clip),
  File "/home/enorrmann/git/superboucle/clip.py", line 190, in channels
    return self.data[clip.audio_file].shape[1]
IndexError: tuple index out of range

**Comment by Zer0-** [comment]
I got the same error loading a mono wav

I applied the following diff:

```diff
diff --git a/clip.py b/clip.py
index 1f801b1..a621e12 100644
--- a/clip.py
+++ b/clip.py
@@ -187,7 +187,11 @@ class Song():
         if clip.audio_file is None:
             return 0
         else:
-            return self.data[clip.audio_file].shape[1]
+            shape = self.data[clip.audio_file].shape
+            if len(shape) == 1:
+                return 1
+            else:
+                return shape[1]
 
     def length(self, clip):
         if clip.audio_file is None:
```

Only to get another error:

```
From cffi callback <function Client.set_process_callback.<locals>.callback_wrapper at 0x7f0c8a1899d8>:
Traceback (most recent call last):
  File "/nix/store/qjcqj19ibj8h1y1pl89529il67c4df05-superboucle-1.2.9/bin/jack.py", line 878, in callback_wrapper
    return callback(frames)
  File "/nix/store/qjcqj19ibj8h1y1pl89529il67c4df05-superboucle-1.2.9/bin/.boucle.py-wrapped", line 111, in my_callback
    length)
  File "/nix/store/qjcqj19ibj8h1y1pl89529il67c4df05-superboucle-1.2.9/bin/clip.py", line 229, in getData
    return (self.data[clip.audio_file][offset:offset + length, channel]
IndexError: too many indices for array
```

I'm trying commit [2955794962f4aaa6b560f05147df618a52e0d0e2](https://github.com/Vampouille/superboucle/commit/2955794962f4aaa6b560f05147df618a52e0d0e2) so I have the line with `always_2d=True` in my code, I checked.

##### File used (gzipped for github support, please unzip):
[india_vocals.wav.gz](https://github.com/Vampouille/superboucle/files/2499967/india_vocals.wav.gz)




Regarding the same commit, I had an issue recording (this should probably go in a separate issue, but I have the traceback handy). I get this while recording:

```
Traceback (most recent call last):
  File "/nix/store/qjcqj19ibj8h1y1pl89529il67c4df05-superboucle-1.2.9/bin/gui.py", line 236, in onStartStopClicked
    self.startStop(clip.x, clip.y)
  File "/nix/store/qjcqj19ibj8h1y1pl89529il67c4df05-superboucle-1.2.9/bin/gui.py", line 250, in startStop
    self.song.init_record_buffer(clip, 2, size, fps)
  File "/nix/store/qjcqj19ibj8h1y1pl89529il67c4df05-superboucle-1.2.9/bin/clip.py", line 263, in init_record_buffer
    dtype=np.float32)
TypeError: 'float' object cannot be interpreted as an integer
Aborted
```
