### ISSUE TITLE
Running on fedora 30

### ISSUE THREAD

**Issue by slyholborn** [Vampouille/superboucle#60]
Hello! i can't make it run en F30 : the stable one is impossible to route in jack and i've got errors wth the git one... 

`./SuperBoucle.sh 
python3: can't open file 'boucle.py': [Errno 2] No such file or directory
`
All deps seems fine? Do i mistake somewhere.? 
Thanks!

**Comment by Vampouille** [comment]
I'm currently working on packaging, so there is some changes. I think that you're using the master branch with #57 merged, you can use pip to install superboucle : 

```bash
$  pip3 install -r requirements.txt
$ python3 setup.py install
```
https://github.com/Vampouille/superboucle/blob/master/Dockerfile#L8-L10

Then you will have a script at `/usr/local/bin/superboucle` to run superboucle.
I will update the readme to include instructions for RPM based distro.

**Comment by damdam-s** [comment]
@slyholborn you can run the `boucle.py` which is in `superboucle` folder at the same level as `SuperBoucle.sh`

**Comment by slyholborn** [comment]
Hello @Vampouille installation works but it won't launch superboucle : 
`Traceback (most recent call last):
  File "/usr/bin/superboucle", line 11, in <module>
    load_entry_point('superboucle==1.2.0', 'console_scripts', 'superboucle')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/superboucle/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/superboucle/clip.py", line 4, in <module>
ImportError: No module named configparser
`
any help? Thanks!

**Comment by Vampouille** [comment]
> any help?

It seems that you try to run superboucle with python version 2, you need python3 to run superboucle. The `configparser` is a standard module of python3:

```bash
$ docker run -ti fedora:30 bash                                                                                                                                                       [17:58:56] 
Unable to find image 'fedora:30' locally
30: Pulling from library/fedora
9908e4690737: Pull complete 
Digest: sha256:8a91dbd4b9d283ca1edc2de5dbeef9267b68bb5dae2335ef64d2db77ddf3aa68
Status: Downloaded newer image for fedora:30
[root@9916d34de78b /]# python3
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>> 
```

**Comment by slyholborn** [comment]
ok! did it by changing the the python version default with 
`# alternatives --install /usr/bin/python python /usr/bin/python3.7 2
# alternatives --install /usr/bin/python python /usr/bin/python2.7 1
`
I get the interface and all sems to work but it disconnects himself from jack as soon as i launch a boucle. Reconnection is the impossible.... an error with wayland? 
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
inotify_add_watch(/home/sylvain/.config/ibus/bus/a56ff8f565dd43fb9c43111d7af7d424-unix-0) failed: (No space left on device)
From cffi callback <function Client.set_process_callback.<locals>.callback_wrapper at 0x7f3e7edb7560>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/superboucle-1.2.0-py3.7.egg/superboucle/jack.py", line 878, in callback_wrapper
  File "/usr/local/lib/python3.7/site-packages/superboucle-1.2.0-py3.7.egg/superboucle/boucle.py", line 145, in my_callback
  File "/usr/local/lib/python3.7/site-packages/superboucle-1.2.0-py3.7.egg/superboucle/clip.py", line 190, in channels
IndexError: tuple index out of range
`

**Comment by Vampouille** [comment]
Interesting to test it on wayland !
 
> did it by changing the the python version default

Cool ! happy to see that you have at least the beautiful interface of superboucle ;-) one step forward ! I think the `setup.py` miss something about the version of python interpreter. After installation superboucle script **should** choose python3, I will try to fix this.
 I notice the message : "(No space left on device)" in your stack trace. Can you retry with some space available or check if your hard drive is really full ?
Additionally, can you tell me the version of superboucle you are using by running `git rev-parse --short HEAD` in the superboucle directory ?

**Comment by Vampouille** [comment]
@slyholborn How do you launch superboucle ? Can you paste this script : `/usr/bin/superboucle` it should looks like:
```python
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'superboucle==1.2.0','console_scripts','superboucle'
__requires__ = 'superboucle==1.2.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('superboucle==1.2.0', 'console_scripts', 'superboucle')()
    )
```
The first line select a v3 python interpreter, Do you have the same line ?

**Comment by slyholborn** [comment]
@Vampouille there is lot of space on this HDD : 61,2 Go

My /usr/local/bin/superboucle after install is : 

```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'superboucle==1.2.0','console_scripts','superboucle'
__requires__ = 'superboucle==1.2.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
	load_entry_point('superboucle==1.2.0', 'console_scripts', 'superboucle')()
    )


```

**Comment by Vampouille** [comment]
Ok so it might related to wayland, did you try to set `QT_QPA_PLATFORM=wayland` as mentioned in the error message:
```bash
QT_QPA_PLATFORM=wayland superboucle
```

I will do some test with wayland.

**Comment by slyholborn** [comment]
I don't know how to do this... But i can try my sessions without wayland...

**Comment by Vampouille** [comment]
You need to install an additional package, on debian it's called `qtwayland5`

**Comment by Vampouille** [comment]
> I don't know how to do this...

Just open a terminal and add `QT_QPA_PLATFORM=wayland` before the `superboucle` command to set an environment variable just for the command. So in a terminal you type:
```
QT_QPA_PLATFORM=wayland superboucle
```
I don't known if this variable is mandatory for your setup, but I think the `qtwayland5`package is required.

**Comment by slyholborn** [comment]
It behaves the same, but the message is now 
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
inotify_add_watch(/home/sylvain/.config/ibus/bus/a56ff8f565dd43fb9c43111d7af7d424-unix-0) failed: (No space left on device)
qt.qpa.wayland: Non-toplevel surfaces can't request window states
From cffi callback <function Client.set_process_callback.<locals>.callback_wrapper at 0x7f32c6547560>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/superboucle-1.2.0-py3.7.egg/superboucle/jack.py", line 878, in callback_wrapper
  File "/usr/local/lib/python3.7/site-packages/superboucle-1.2.0-py3.7.egg/superboucle/boucle.py", line 145, in my_callback
  File "/usr/local/lib/python3.7/site-packages/superboucle-1.2.0-py3.7.egg/superboucle/clip.py", line 190, in channels
IndexError: tuple index out of range
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Non-toplevel surfaces can't request window states

```

**Comment by slyholborn** [comment]
I also have issues with the left menu : windows with bpm etc are not well positionned .

**Comment by Vampouille** [comment]
> IndexError: tuple index out of range

This issue is now fixed on master. Can you update your local clone and retry ?

**Comment by slyholborn** [comment]
Ok! I'll try it right now!

**Comment by slyholborn** [comment]
It installs, connects to jack, but still this window issue and... i have no sound although all seems good... still trying!

**Comment by slyholborn** [comment]
`qt.qpa.wayland: Non-toplevel surfaces can't request window states`

**Comment by slyholborn** [comment]
On arrete tout!! j'ai du son!!! Sorry, I've got sound : i just made mistake with my sound cards routings...  everything works well except issues withe the left menu.

**Comment by Vampouille** [comment]
> everything works well except issues withe the left menu.

Can you create a separate issue for issue about left menu with a screenshot ?

**Comment by slyholborn** [comment]
Sure!
