### ISSUE TITLE
Fail to launch

### ISSUE THREAD

**Issue by trebmuh** [Vampouille/superboucle#62]
Salut Vampouille.

J'ai enfin trouvé du temps pour tenter un empaquetage de SuperBoucle pour la future LibraZiK-3.
Le paquet semble se construire correctement, mais superboucle ne se lance pas et me met un:
```
$ superboucle
Traceback (most recent call last):
  File "/usr/bin/superboucle", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5>=5.11' distribution was not found and is required by superboucle
```

Une idée ?

_Édition : précision, c'est sur une base Debian Buster, et pyqt5 est en version 5.11.3+dfsg-1+b3_

**Comment by Vampouille** [comment]
Tu dois retirer PyQt5 des dépendances dans le fichier `setup.py`. PyQt5 n'est pas "visible" comme package python installé mais on peut le charger. C'est une particularité du packaging de PyQt5. Y'a un patch ici : 
I think you need to remove PyQt5 from setup.py. see the following patch for building deb package :
https://github.com/Vampouille/superboucle/blob/master/setup.py.debian.patch
Used here :
https://github.com/Vampouille/superboucle/blob/master/Makefile#L18

**Comment by trebmuh** [comment]
Super, ça fonctionne maintenant !
Merci.
